name: Run plugin workflow

on:
    pull_request:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    call-plugin-workflow:
        strategy:
            matrix:
                include:
                    - shopware-version: 5.7.4
                      php-version: 8.0
                    - shopware-version: 5.7
                      php-version: 7.4
                    - shopware-version: 5.7
                      php-version: 8.2

        uses: shopware5/docker-images-testing/.github/workflows/plugin-workflow.yml@main
        with:
            plugin-name: SwagImportExport
            php-version: ${{ matrix.php-version }}
            shopware-version: ${{ matrix.shopware-version }}f
